version: 2.1
orbs:
  dotnet-tools: bwp-orbs/dotnet-tools@30.0.0
  
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1
    steps:
      - checkout
      - run:
          name: Restore solution
          command: dotnet restore 
      - run:
          name: Build solution
          command: dotnet build   
      - run:
          command: |
            dotnet test \
              --logger trx \
              -r ~/repo/Tests/results \
              /p:CollectCoverage=true \
              /p:CoverletOutputFormat=opencover \
              /p:CoverletOutput=/root/repo/Tests/results/ \
              /p:Exclude="[MySqlConnector]*%2c[System.*]*"
          name: Unit Test
      - run:
          command: |
            reportgenerator \
              -reports:/root/repo/Tests/results/coverage.opencover.xml \
              -targetdir:/root/repo/Tests/results/html_report \
              -verbosity:Off
          name: Generate code coverage report
      - run:
          command: |
            trx2junit ~/repo/Tests/results/*.trx
          name: Convert test results to junit format
          when: always
      - store_test_results:
          path: ~/repo/Tests/results
      - store_artifacts:
          destination: TestResults
          path: ~/repo/Tests/results
      - save_cache:
          key: >-
            v1-unit-test-coverage-{{ .Environment.CIRCLE_BRANCH }}-{{
            .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/repo/Tests/results
     
